<a href="https://colab.research.google.com/github/2303A52445/Generative-AI/blob/main/GAI_ass_8_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
import joblib

# Load dataset
dataset_path = "/content/winequality-red.csv"  # Change if needed
df = pd.read_csv(dataset_path)

# Separate features and target
X = df.drop(columns=["quality"])
y = df["quality"]

# Convert target to categorical if necessary (for classification)
y = pd.cut(y, bins=[0, 5, 6, 10], labels=[0, 1, 2])  # Adjust based on dataset
y = keras.utils.to_categorical(y)

# Split dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Standardize features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Save scaler
joblib.dump(scaler, "scaler.pkl")

# Build ANN model
model = Sequential([
    Dense(12, activation='tanh', input_shape=(X_train.shape[1],)),
    Dense(24, activation='tanh'),
    Dense(30, activation='tanh'),
    Dense(20, activation='tanh'),
    Dense(10, activation='tanh'),
    Dense(y.shape[1], activation='softmax')  # Output layer for classification
])

# Compile model
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# Train model
history = model.fit(X_train, y_train, epochs=200, batch_size=32, validation_data=(X_test, y_test))

# Save model
model.save("wine_quality_model.h5")

# Evaluate model
y_pred = model.predict(X_test)
y_pred_classes = np.argmax(y_pred, axis=1)
y_true = np.argmax(y_test, axis=1)

# Calculate metrics
acc = accuracy_score(y_true, y_pred_classes)
cm = confusion_matrix(y_true, y_pred_classes)
report = classification_report(y_true, y_pred_classes)

print(f"Accuracy: {acc}")
print("Confusion Matrix:\n", cm)
print("Classification Report:\n", report)

# Deploy model: Load and predict
def load_model_and_predict(sample_input):
    loaded_model = keras.models.load_model("wine_quality_model.h5")
    loaded_scaler = joblib.load("scaler.pkl")
    sample_input = loaded_scaler.transform([sample_input])
    prediction = loaded_model.predict(sample_input)
    return np.argmax(prediction)

# Example usage
sample_input = X_test[0]
predicted_class = load_model_and_predict(sample_input)
print("Predicted Wine Quality Category:", predicted_class)

Epoch 1/200


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


40/40 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - accuracy: 0.4490 - loss: 1.0460 - val_accuracy: 0.5469 - val_loss: 0.8907
Epoch 2/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6073 - loss: 0.8345 - val_accuracy: 0.5531 - val_loss: 0.8361
Epoch 3/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6109 - loss: 0.8158 - val_accuracy: 0.5813 - val_loss: 0.8123
Epoch 4/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6226 - loss: 0.7849 - val_accuracy: 0.5844 - val_loss: 0.7929
Epoch 5/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.6235 - loss: 0.7819 - val_accuracy: 0.5781 - val_loss: 0.7903
Epoch 6/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6379 - loss: 0.7547 - val_accuracy: 0.6094 - val_loss: 0.7802
Epoch 7/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.6554 - loss: 0.7745 - val_accuracy: 0.6031 - val_loss: 0.7782
Epoch 8/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.6542 - loss: 0.7399 - val_accuracy: 0.5969 - val_loss: 0.

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step 


Accuracy: 0.690625
Confusion Matrix:
 [[109  30   2]
 [ 40  79  13]
 [  3  11  33]]
Classification Report:
               precision    recall  f1-score   support

           0       0.72      0.77      0.74       141
           1       0.66      0.60      0.63       132
           2       0.69      0.70      0.69        47

    accuracy                           0.69       320
   macro avg       0.69      0.69      0.69       320
weighted avg       0.69      0.69      0.69       320

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step
Predicted Wine Quality Category: 0


/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
